name: test
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: app
      # - name: SwiftLint
      #   uses: norio-nomura/action-swiftlint@3.2.1
      - name: Run tests with Thread Sanitizer
        env:
            SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --parallel --enable-code-coverage --sanitize=thread
        working-directory: app
      - name: Test summary
        run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
      # - name: Code coverage
      #   uses: maxep/spm-lcov-action@0.3.0
      #   with:
      #     output-file: ./coverage/lcov.info