name: test
run-name: ${{ github.actor }} is running test workflow
on: [push]
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
    

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: app
      
      - name: Run tests with Thread Sanitizer
        env:
            SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --parallel --enable-code-coverage --sanitize=thread
        working-directory: app

      - name: Log test
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::warning file=Sources/test/test.swift,line=6,col=29,endColumn=33::Missing semicolon"
            echo "::endgroup::"

      - name: Test summary
        run: |

            echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
            echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
            echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
            echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
            cat README.md >> $GITHUB_STEP_SUMMARY
      
  hello-world:
    runs-on: self-hosted
    steps:
      - name: Hello
        run: |
            echo "Hello, world!"
            echo "::notice file=test.swift,line=1,col=5,endColumn=7::Missing semicolon"
            echo "Summary example" >> $GITHUB_STEP_SUMMARY

      # - name: SwiftLint
      #   uses: norio-nomura/action-swiftlint@3.2.1

      # - name: Code coverage
      #   uses: maxep/spm-lcov-action@0.3.0
      #   with:
      #     output-file: ./coverage/lcov.info